#!/bin/bash

# .cfg SU2 file
cfgFile="testingChan.cfg"

# own SU2_CFD directory with executable
ownSU2_CFD=$HOME"/madLabSU2/ownSU2facility/Exec/bin//SU2_CFD"

# own SU2_SOL directory with executable
ownSU2_SOL=$HOME"/madLabSU2/ownSU2facility/Exec/bin/SU2_SOL"

# create folder directories for runtime, postprocessing and logging
mkdir "time" "processed" "logFiles"

# start solver
$ownSU2_CFD $cfgFile >& logFiles/run.log &

# post-process solution
$ownSU2_SOL $cfgFile >& logFiles/process.log &
